//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 09:38:19 AM EET 
//


package com.example.springdemo.soap;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for activity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="activity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startActivity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endActivity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patientUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "activity", propOrder = {
    "id",
    "activity",
    "startActivity",
    "endActivity",
    "patientUsername"
})
public class Activity {

    @XmlElement(required = true)
    protected BigDecimal id;
    @XmlElement(required = true)
    protected String activity;
    @XmlElement(required = true)
    protected String startActivity;
    @XmlElement(required = true)
    protected String endActivity;
    @XmlElement(required = true)
    protected String patientUsername;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setId(BigDecimal value) {
        this.id = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivity(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the startActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartActivity() {
        return startActivity;
    }

    /**
     * Sets the value of the startActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartActivity(String value) {
        this.startActivity = value;
    }

    /**
     * Gets the value of the endActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndActivity() {
        return endActivity;
    }

    /**
     * Sets the value of the endActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndActivity(String value) {
        this.endActivity = value;
    }

    /**
     * Gets the value of the patientUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientUsername() {
        return patientUsername;
    }

    /**
     * Sets the value of the patientUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientUsername(String value) {
        this.patientUsername = value;
    }

}
