//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 09:38:19 AM EET 
//


package com.example.springdemo.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.springdemo.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.springdemo.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetMedicalrecordRequest }
     * 
     */
    public GetMedicalrecordRequest createGetMedicalrecordRequest() {
        return new GetMedicalrecordRequest();
    }

    /**
     * Create an instance of {@link GetActivitiesRequest }
     * 
     */
    public GetActivitiesRequest createGetActivitiesRequest() {
        return new GetActivitiesRequest();
    }

    /**
     * Create an instance of {@link GetDoctorResponse }
     * 
     */
    public GetDoctorResponse createGetDoctorResponse() {
        return new GetDoctorResponse();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetActivitiesResponse }
     * 
     */
    public GetActivitiesResponse createGetActivitiesResponse() {
        return new GetActivitiesResponse();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link GetDoctorRequest }
     * 
     */
    public GetDoctorRequest createGetDoctorRequest() {
        return new GetDoctorRequest();
    }

    /**
     * Create an instance of {@link GetMedicalrecordResponse }
     * 
     */
    public GetMedicalrecordResponse createGetMedicalrecordResponse() {
        return new GetMedicalrecordResponse();
    }

    /**
     * Create an instance of {@link Medicalrecord }
     * 
     */
    public Medicalrecord createMedicalrecord() {
        return new Medicalrecord();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link Drug }
     * 
     */
    public Drug createDrug() {
        return new Drug();
    }

    /**
     * Create an instance of {@link DrugSideEffect }
     * 
     */
    public DrugSideEffect createDrugSideEffect() {
        return new DrugSideEffect();
    }

}
